### PR TITLE
Integrate firebase authentication + Home page with tabs

### PR DESCRIPTION
**Pull request by shivaneej**
This PR has the following UIs:
- Sign in page with the logo and google login + firebase authentication
- On successful login the user is redirected to the homepage with custom tab bar
- 4 views on the custom tab bar - home, prompt, log and user profile

Addresses issues #1 and #4

### CODE REVIEW

**Comment by tgag17** [comment]
Looks good to me!

**Review by tgag17 — APPROVED** [review]

**Review by alexcflorea — APPROVED** [review]
Looks good to me! 👍

**Review by pratikshappai — APPROVED** [review]
great work on the UI, thanks!

**Comment by alexcflorea** [comment]
Fantastic job, Shivanee!

**Pull request merged**
